{
 "title": "air-Q Prometheus Exporter",
 "time": { "from": "2024-02-08T00:54:24.629Z", "to": "2024-02-24T15:21:12.396Z" },
 "panels": [
  {
   "title": "Health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "airq_health / 10", "legendFormat": "Health" }
   ]
  },
  {
   "title": "Health",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_health / 10", "legendFormat": "Health" }
   ]
  },
  {
   "title": "Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "airq_performance / 10", "legendFormat": "Performance" }
   ]
  },
  {
   "title": "Performance",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_performance / 10", "legendFormat": "Health" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "airq_humidity", "legendFormat": "Relative Humidity" },
    { "expr": "airq_humidity_abs", "legendFormat": "Absolute Humidity" }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_humidity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Change of Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "airq_dHdt", "legendFormat": "Change of Humidity" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "airq_temperature", "legendFormat": "Temperature" },
    { "expr": "airq_temperature_error_margin", "legendFormat": "Temperature Error Margin" }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Volatile Organic Compounds (VOC)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    { "expr": "airq_tvoc", "legendFormat": "VOC" }
   ]
  },
  {
   "title": "Carbon Dioxide (CO₂)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "airq_co2", "legendFormat": "Carbon Dioxide" },
    { "expr": "airq_co2_error_margin", "legendFormat": "Carbon Dioxide Error Margin" }
   ]
  },
  {
   "title": "Carbon Dioxide (CO₂)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_co2", "legendFormat": "Carbon Dioxide" }
   ]
  },
  {
   "title": "Change of CO2 Concentration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "airq_dCO2dt", "legendFormat": "Change of CO2 Concentration" }
   ]
  },
  {
   "title": "Carbon Monoxide (CO)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "conmgm3" } },
   "targets": [
    { "expr": "airq_co", "legendFormat": "Carbon Monoxide" },
    { "expr": "airq_co_error_margin", "legendFormat": "Carbon Monoxide Error Margin" }
   ]
  },
  {
   "title": "Carbon Monoxide (CO)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 2, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "conmgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_co", "legendFormat": "Carbon Monoxide" }
   ]
  },
  {
   "title": "Noise",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "airq_sound", "legendFormat": "Noise" },
    { "expr": "avg_over_time(airq_sound[10m])", "legendFormat": "Noise (Average 10 min)" },
    { "expr": "airq_sound_max", "legendFormat": "Noise (Maximum)" },
    {
     "expr": "avg_over_time(airq_sound_max[10m])",
     "legendFormat": "Noise (Maximum, Average 10 min)"
    }
   ]
  },
  {
   "title": "Nitrogen Dioxide (NO₂)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "airq_no2", "legendFormat": "Nitrogen Dioxide" },
    { "expr": "airq_no2_error_margin", "legendFormat": "Nitrogen Dioxide Error Margin" }
   ]
  },
  {
   "title": "Nitrogen Dioxide (NO₂)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airq_no2", "legendFormat": "Nitrogen Dioxide" }
   ]
  },
  {
   "title": "Particulate Matter (5m Average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "avg_over_time(airq_pm1[5m])", "legendFormat": "Particulates PM1" },
    { "expr": "avg_over_time(airq_pm2_5[5m])", "legendFormat": "Particulates PM2,5" },
    { "expr": "avg_over_time(airq_pm10[5m])", "legendFormat": "Particulates PM10" },
    { "expr": "avg_over_time(airq_TypPS[1h])", "legendFormat": "Typical Particulate Size" }
   ]
  },
  {
   "title": "Typical Particulate Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "avg_over_time(airq_TypPS[1h])", "legendFormat": "Typical Particulate Size" }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "airq_pressure", "legendFormat": "Atmospheric Pressure" },
    {
     "expr": "airq_pressure_error_margin",
     "legendFormat": "Atmospheric Pressure Error Margin"
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "airq_dewpt", "legendFormat": "Dew Point" },
    { "expr": "airq_dewpt_error_margin", "legendFormat": "Dew Point Error Margin" }
   ]
  },
  {
   "title": "Measure Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "airq_measuretime", "legendFormat": "Measure Time" },
    {
     "expr": "avg_over_time(airq_measuretime[10m])",
     "legendFormat": "Measure Time (Average 10 Minutes)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(time() - airq_uptime) * 1000", "legendFormat": "Up Since" },
    { "expr": "airq_uptime", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Typical Particulate Size",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 67 },
   "targets": [
    { "expr": "airq_TypPS", "legendFormat": "Typical Particulate Size" }
   ]
  }
 ]
}