name: Java CI with Maven

on: [ push, pull_request ]

jobs:
  build-non-macos:

    strategy:
      matrix:
        java-version: [ 24 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn clean package --batch-mode --threads 4
